import { Topic } from './domain';

export const quantTopics: Topic[] = [
  { id: 'q_arith', title: 'Arithmetic', estimatedQCount: 5, importance: 'high', tags: ['numerical'],
    subtopics: ['Percentages', 'Profit & Loss', 'Simple & Compound Interest', 'Time, Speed & Distance', 'Time & Work', 'Averages', 'Ratios & Proportions'],
  },
  { id: 'q_di', title: 'Data Interpretation', estimatedQCount: 5, importance: 'high', tags: ['numerical', 'graph-reading'],
    subtopics: ['Bar Charts', 'Line Graphs', 'Pie Charts', 'Data Tables', 'Caselets'],
  },
  { id: 'q_algebra', title: 'Algebra & Number Systems', estimatedQCount: 4, importance: 'high', tags: ['formula-heavy'],
    subtopics: ['Number Series', 'HCF & LCM', 'Surds & Indices', 'Quadratic Equations', 'Progressions — AP, GP'],
  },
  { id: 'q_geo', title: 'Geometry & Mensuration', estimatedQCount: 3, importance: 'medium', tags: ['formula-heavy'],
    subtopics: ['Area & Perimeter of 2D Figures', 'Volume of 3D Solids', 'Triangles & Circles', 'Coordinate Geometry Basics'],
  },
  { id: 'q_prob', title: 'Probability & Permutation-Combination', estimatedQCount: 3, importance: 'medium', tags: ['numerical'],
    subtopics: ['Basic Probability', 'Conditional Probability', 'Permutations', 'Combinations', 'Bayes Theorem'],
  },
  { id: 'q_mixture', title: 'Mixtures & Alligation', estimatedQCount: 2, importance: 'high', tags: ['numerical'],
    subtopics: ['Alligation Rule', 'Mixing Two Mixtures', 'Successive Dilution', 'Mean Price Problems', 'Replacement of Liquid'],
  },
  { id: 'q_misc', title: 'Clocks, Calendars & Miscellaneous', estimatedQCount: 2, importance: 'medium', tags: ['numerical'],
    subtopics: ['Clock Angles & Coincidences', 'Calendar — Day Finding', 'Boats & Streams', 'Pipes & Cisterns', 'Train Problems'],
  },
];

export const reasoningTopics: Topic[] = [
  { id: 'r_series', title: 'Number & Letter Series', estimatedQCount: 4, importance: 'high', tags: ['conceptual'],
    subtopics: ['Number Series — Missing Term', 'Letter Series & Alphabetical Patterns', 'Alphanumeric Series', 'Odd One Out in Series'],
  },
  { id: 'r_analogy', title: 'Analogy & Classification', estimatedQCount: 3, importance: 'high', tags: ['conceptual'],
    subtopics: ['Number Analogies', 'Letter Analogies', 'Word Analogies', 'Odd One Out Classification'],
  },
  { id: 'r_coding', title: 'Coding-Decoding', estimatedQCount: 3, importance: 'high', tags: ['conceptual'],
    subtopics: ['Letter Coding', 'Number Coding', 'Mixed Coding', 'Decoding Messages'],
  },
  { id: 'r_blood', title: 'Blood Relations', estimatedQCount: 2, importance: 'medium', tags: ['conceptual'],
    subtopics: ['Family Tree Problems', 'Coded Blood Relations', 'Mixed Blood Relation Questions'],
  },
  { id: 'r_direction', title: 'Direction Sense', estimatedQCount: 2, importance: 'medium', tags: ['conceptual'],
    subtopics: ['Simple Direction Problems', 'Shadow & Rotation Problems', 'Distance Calculation'],
  },
  { id: 'r_puzzle', title: 'Puzzles & Seating Arrangement', estimatedQCount: 5, importance: 'high', tags: ['conceptual'],
    subtopics: ['Linear Seating', 'Circular Seating', 'Floor-Based Puzzles', 'Box & Stack Puzzles', 'Scheduling Puzzles'],
  },
  { id: 'r_syllogism', title: 'Syllogism & Statement-Conclusion', estimatedQCount: 3, importance: 'high', tags: ['conceptual'],
    subtopics: ['Venn Diagram Method', 'Statement & Conclusions', 'Statement & Assumptions', 'Statement & Courses of Action'],
  },
  { id: 'r_data_suff', title: 'Data Sufficiency', estimatedQCount: 2, importance: 'medium', tags: ['conceptual', 'numerical'],
    subtopics: ['Mathematical Data Sufficiency', 'Logical Data Sufficiency'],
  },
  { id: 'r_input', title: 'Input-Output & Coding', estimatedQCount: 2, importance: 'medium', tags: ['conceptual'],
    subtopics: ['Machine Input-Output Problems', 'Ranking & Order', 'Inequality Problems'],
  },
  { id: 'r_nonverbal', title: 'Non-Verbal Reasoning', estimatedQCount: 4, importance: 'medium', tags: ['conceptual'],
    subtopics: ['Pattern Completion', 'Mirror & Water Images', 'Embedded Figures', 'Paper Folding & Cutting', 'Cubes & Dice'],
  },
  { id: 'r_ranking', title: 'Ranking, Ordering & Inequalities', estimatedQCount: 3, importance: 'high', tags: ['conceptual'],
    subtopics: ['Linear Ranking', 'Circular Order', 'Mathematical Inequalities (>, <, ≥)', 'Double Row Rankings', 'Combined Ranking-Direction'],
  },
  { id: 'r_venn', title: 'Venn Diagrams & Set Theory', estimatedQCount: 2, importance: 'medium', tags: ['conceptual'],
    subtopics: ['2-Set Venn Problems', '3-Set Venn Problems', 'Set Notation & Operations', 'Syllogism via Venn Method', 'Data-Based Venn Problems'],
  },
];

export const englishTopics: Topic[] = [
  { id: 'en_grammar', title: 'Grammar & Usage', estimatedQCount: 5, importance: 'high', tags: ['memory'],
    subtopics: ['Tenses — All Forms', 'Subject-Verb Agreement', 'Articles — A, An, The', 'Prepositions', 'Conjunctions', 'Active & Passive Voice', 'Direct & Indirect Speech'],
  },
  { id: 'en_vocab', title: 'Vocabulary', estimatedQCount: 4, importance: 'high', tags: ['memory'],
    subtopics: ['Synonyms & Antonyms', 'Idioms & Phrases', 'One-Word Substitution', 'Word Meanings in Context'],
  },
  { id: 'en_rc', title: 'Reading Comprehension', estimatedQCount: 5, importance: 'high', tags: ['conceptual'],
    subtopics: ['Main Idea & Title', 'Inference & Conclusion', 'Tone & Mood of Passage', 'Vocabulary in Context'],
  },
  { id: 'en_sentence', title: 'Sentence Improvement & Error Spotting', estimatedQCount: 4, importance: 'high', tags: ['memory'],
    subtopics: ['Error Spotting — Grammatical Errors', 'Sentence Improvement', 'Sentence Rearrangement (Para Jumbles)', 'Fill in the Blanks'],
  },
  { id: 'en_verbal', title: 'Verbal Ability', estimatedQCount: 2, importance: 'medium', tags: ['conceptual', 'memory'],
    subtopics: ['Cloze Test', 'Paragraph Completion', 'Word Usage — Correct/Incorrect'],
  },
];

export const gkTopics: Topic[] = [
  { id: 'gk_current', title: 'Current Affairs', estimatedQCount: 6, importance: 'high', tags: ['memory'],
    subtopics: ['National Events & Policies (Last 6 months)', 'International Affairs', 'Sports — Major Championships', 'Awards — Padma, Nobel, Oscars', 'Appointments — Cabinet, PSU Chiefs'],
  },
  { id: 'gk_economy', title: 'Indian Economy & Finance', estimatedQCount: 4, importance: 'high', tags: ['conceptual', 'memory'],
    subtopics: ['Budget Highlights', 'GDP, Inflation, Monetary Policy', 'Five Year Plans & NITI Aayog', 'Major Schemes — PLI, Make in India', 'Trade & Balance of Payments'],
  },
  { id: 'gk_polity', title: 'Indian Polity & Constitution', estimatedQCount: 4, importance: 'medium', tags: ['memory'],
    subtopics: ['Fundamental Rights & Duties', 'Parliament & State Legislature', 'Constitutional Bodies — CAG, EC', 'Amendment Process', 'Important Articles'],
  },
  { id: 'gk_science', title: 'Science & Technology', estimatedQCount: 3, importance: 'medium', tags: ['conceptual', 'memory'],
    subtopics: ['Space Missions — ISRO, NASA', 'Nuclear Energy & Defence', 'Biotechnology & Medical Discoveries', 'AI & Digital India'],
  },
  { id: 'gk_geo', title: 'Indian Geography', estimatedQCount: 2, importance: 'low', tags: ['memory'],
    subtopics: ['Rivers & Watersheds', 'National Parks & Biosphere Reserves', 'Mineral Resources', 'Climate & Agriculture'],
  },
  { id: 'gk_history', title: 'History & Culture', estimatedQCount: 1, importance: 'low', tags: ['memory'],
    subtopics: ['Freedom Movement Key Events', 'Ancient & Medieval India Highlights', 'Art & Architecture'],
  },
  { id: 'gk_psu', title: 'PSU & Energy Sector Knowledge', estimatedQCount: 4, importance: 'high', tags: ['memory'],
    subtopics: ['Navratna / Maharatna / Miniratna Status', 'Key PSU HQs, CMDs, Capacities', 'Energy Policy — Net Zero, INDCs, MNRE Targets', 'Oil & Gas Sector — OPEC, IEA, LNG Trade', 'Coal & Mining — CIL Subsidiaries, Coal Blocks', 'Power Sector — Installed Capacity, NTPC/POWERGRID Projects'],
  },
];
