import { Topic } from './domain';

// ─────────────────────────────────────────────────────────────────────────────
// Schooling (Class 9–12) syllabus — complete NCERT/CBSE chapters as Topics.
// Section ids are globally unique (subject+class) so the resolver looks them up
// directly. Subjects: Science/Maths/Social Science/English (9–10),
// Physics/Chemistry/Maths/Biology/English (11–12).
// ─────────────────────────────────────────────────────────────────────────────

// ══════════════════════════════ CLASS 9 ══════════════════════════════════════

export const sci9Topics: Topic[] = [
  { id: 'sci9_matter', title: 'Matter in Our Surroundings', estimatedQCount: 5, importance: 'high', tags: ['conceptual'],
    subtopics: ['States of Matter', 'Change of State', 'Evaporation & Latent Heat'] },
  { id: 'sci9_pure', title: 'Is Matter Around Us Pure', estimatedQCount: 5, importance: 'high', tags: ['conceptual'],
    subtopics: ['Mixtures & Solutions', 'Separation Techniques', 'Colloids & Suspensions'] },
  { id: 'sci9_atoms', title: 'Atoms and Molecules', estimatedQCount: 5, importance: 'high', tags: ['numerical', 'conceptual'],
    subtopics: ['Laws of Chemical Combination', 'Mole Concept', 'Atomic & Molecular Mass'] },
  { id: 'sci9_atom_struct', title: 'Structure of the Atom', estimatedQCount: 5, importance: 'high', tags: ['conceptual'],
    subtopics: ['Subatomic Particles', 'Bohr Model', 'Valency', 'Isotopes & Isobars'] },
  { id: 'sci9_cell', title: 'The Fundamental Unit of Life', estimatedQCount: 5, importance: 'high', tags: ['memory', 'conceptual'],
    subtopics: ['Cell Organelles', 'Plant vs Animal Cell', 'Osmosis & Diffusion'] },
  { id: 'sci9_tissues', title: 'Tissues', estimatedQCount: 4, importance: 'medium', tags: ['memory'],
    subtopics: ['Plant Tissues', 'Animal Tissues', 'Meristematic vs Permanent'] },
  { id: 'sci9_motion', title: 'Motion', estimatedQCount: 6, importance: 'high', tags: ['numerical', 'formula-heavy'],
    subtopics: ['Distance & Displacement', 'Equations of Motion', 'Graphs of Motion'] },
  { id: 'sci9_force', title: 'Force and Laws of Motion', estimatedQCount: 6, importance: 'high', tags: ['numerical', 'conceptual'],
    subtopics: ["Newton's Laws", 'Inertia & Momentum', 'Conservation of Momentum'] },
  { id: 'sci9_gravitation', title: 'Gravitation', estimatedQCount: 5, importance: 'high', tags: ['numerical', 'formula-heavy'],
    subtopics: ['Universal Law', 'Free Fall', 'Thrust & Pressure', 'Archimedes Principle'] },
  { id: 'sci9_work', title: 'Work and Energy', estimatedQCount: 5, importance: 'high', tags: ['numerical', 'formula-heavy'],
    subtopics: ['Work', 'Kinetic & Potential Energy', 'Power', 'Conservation of Energy'] },
  { id: 'sci9_sound', title: 'Sound', estimatedQCount: 4, importance: 'medium', tags: ['conceptual', 'numerical'],
    subtopics: ['Wave Properties', 'Reflection & Echo', 'SONAR', 'Human Ear'] },
  { id: 'sci9_food', title: 'Improvement in Food Resources', estimatedQCount: 3, importance: 'low', tags: ['memory'],
    subtopics: ['Crop Production', 'Animal Husbandry', 'Manures & Fertilizers'] },
];

export const math9Topics: Topic[] = [
  { id: 'math9_number', title: 'Number Systems', estimatedQCount: 5, importance: 'high', tags: ['conceptual', 'numerical'],
    subtopics: ['Rational & Irrational Numbers', 'Real Numbers on Number Line', 'Laws of Exponents'] },
  { id: 'math9_poly', title: 'Polynomials', estimatedQCount: 5, importance: 'high', tags: ['formula-heavy'],
    subtopics: ['Degree & Zeroes', 'Remainder & Factor Theorem', 'Algebraic Identities'] },
  { id: 'math9_coord', title: 'Coordinate Geometry', estimatedQCount: 3, importance: 'medium', tags: ['conceptual'],
    subtopics: ['Cartesian Plane', 'Plotting Points', 'Quadrants'] },
  { id: 'math9_linear', title: 'Linear Equations in Two Variables', estimatedQCount: 4, importance: 'high', tags: ['numerical'],
    subtopics: ['Solutions of Linear Equations', 'Graph of a Line'] },
  { id: 'math9_euclid', title: "Introduction to Euclid's Geometry", estimatedQCount: 2, importance: 'low', tags: ['conceptual'],
    subtopics: ['Axioms & Postulates', "Euclid's Definitions"] },
  { id: 'math9_lines', title: 'Lines and Angles', estimatedQCount: 4, importance: 'high', tags: ['conceptual'],
    subtopics: ['Pairs of Angles', 'Parallel Lines & Transversal', 'Angle Sum Property'] },
  { id: 'math9_triangles', title: 'Triangles', estimatedQCount: 5, importance: 'high', tags: ['conceptual'],
    subtopics: ['Congruence Criteria', 'Properties of Triangles', 'Inequalities in a Triangle'] },
  { id: 'math9_quad', title: 'Quadrilaterals', estimatedQCount: 4, importance: 'medium', tags: ['conceptual'],
    subtopics: ['Properties of Parallelogram', 'Mid-point Theorem'] },
  { id: 'math9_circles', title: 'Circles', estimatedQCount: 4, importance: 'medium', tags: ['conceptual'],
    subtopics: ['Chords & Arcs', 'Cyclic Quadrilaterals', 'Angle Subtended'] },
  { id: 'math9_heron', title: "Heron's Formula", estimatedQCount: 3, importance: 'medium', tags: ['formula-heavy', 'numerical'],
    subtopics: ['Area of Triangle', 'Application to Quadrilaterals'] },
  { id: 'math9_surface', title: 'Surface Areas and Volumes', estimatedQCount: 5, importance: 'high', tags: ['formula-heavy', 'numerical'],
    subtopics: ['Cuboid & Cylinder', 'Cone & Sphere', 'Hemisphere'] },
  { id: 'math9_stats', title: 'Statistics', estimatedQCount: 3, importance: 'medium', tags: ['numerical', 'graph-reading'],
    subtopics: ['Frequency Distribution', 'Bar Graphs & Histograms', 'Mean, Median, Mode'] },
];

export const sst9Topics: Topic[] = [
  // History — India and the Contemporary World I
  { id: 'sst9_french', title: 'The French Revolution', estimatedQCount: 4, importance: 'high', tags: ['memory'],
    subtopics: ['Causes', 'Rise of Napoleon', 'Legacy'] },
  { id: 'sst9_russia', title: 'Socialism in Europe & the Russian Revolution', estimatedQCount: 4, importance: 'high', tags: ['memory'],
    subtopics: ['Russian Revolution', 'Rise of Socialism', 'Stalinism'] },
  { id: 'sst9_nazism', title: 'Nazism and the Rise of Hitler', estimatedQCount: 3, importance: 'medium', tags: ['memory'],
    subtopics: ['Weimar Republic', "Hitler's Rise", 'Nazi Ideology'] },
  { id: 'sst9_forest', title: 'Forest Society and Colonialism', estimatedQCount: 2, importance: 'low', tags: ['memory'],
    subtopics: ['Deforestation', 'Forest Rules', 'Rebellion in the Forest'] },
  { id: 'sst9_pastoral', title: 'Pastoralists in the Modern World', estimatedQCount: 2, importance: 'low', tags: ['memory'],
    subtopics: ['Nomadic Pastoralists', 'Colonial Rule & Pastoral Life'] },
  // Geography — Contemporary India I
  { id: 'sst9_india_size', title: 'India — Size and Location', estimatedQCount: 3, importance: 'medium', tags: ['memory'],
    subtopics: ['Latitudinal Extent', 'Neighbours', 'Standard Meridian'] },
  { id: 'sst9_physical', title: 'Physical Features of India', estimatedQCount: 3, importance: 'medium', tags: ['memory'],
    subtopics: ['Himalayas', 'Northern Plains', 'Peninsular Plateau'] },
  { id: 'sst9_drainage', title: 'Drainage', estimatedQCount: 3, importance: 'medium', tags: ['memory'],
    subtopics: ['Himalayan Rivers', 'Peninsular Rivers', 'Lakes'] },
  { id: 'sst9_climate', title: 'Climate', estimatedQCount: 3, importance: 'medium', tags: ['conceptual', 'memory'],
    subtopics: ['Monsoon', 'Factors Affecting Climate', 'Seasons'] },
  { id: 'sst9_vegetation', title: 'Natural Vegetation and Wildlife', estimatedQCount: 2, importance: 'low', tags: ['memory'],
    subtopics: ['Types of Vegetation', 'Wildlife', 'Conservation'] },
  { id: 'sst9_population', title: 'Population', estimatedQCount: 2, importance: 'medium', tags: ['conceptual'],
    subtopics: ['Density & Distribution', 'Growth & Composition'] },
  // Civics — Democratic Politics I
  { id: 'sst9_democracy', title: 'What is Democracy? Why Democracy?', estimatedQCount: 3, importance: 'high', tags: ['conceptual'],
    subtopics: ['Features of Democracy', 'Arguments For & Against'] },
  { id: 'sst9_constitution', title: 'Constitutional Design', estimatedQCount: 3, importance: 'medium', tags: ['memory'],
    subtopics: ['Making of the Constitution', 'Guiding Values', 'Preamble'] },
  { id: 'sst9_electoral', title: 'Electoral Politics', estimatedQCount: 2, importance: 'medium', tags: ['conceptual'],
    subtopics: ['Elections', 'Election Commission', 'Voting'] },
  { id: 'sst9_institutions', title: 'Working of Institutions', estimatedQCount: 2, importance: 'medium', tags: ['memory'],
    subtopics: ['Legislature', 'Executive', 'Judiciary'] },
  { id: 'sst9_rights', title: 'Democratic Rights', estimatedQCount: 2, importance: 'medium', tags: ['conceptual'],
    subtopics: ['Fundamental Rights', 'Importance of Rights'] },
  // Economics
  { id: 'sst9_palampur', title: 'The Story of Village Palampur', estimatedQCount: 2, importance: 'medium', tags: ['conceptual'],
    subtopics: ['Factors of Production', 'Farming & Non-farm Activities'] },
  { id: 'sst9_people', title: 'People as Resource', estimatedQCount: 2, importance: 'medium', tags: ['conceptual'],
    subtopics: ['Human Capital', 'Education & Health', 'Unemployment'] },
  { id: 'sst9_poverty', title: 'Poverty as a Challenge', estimatedQCount: 2, importance: 'medium', tags: ['conceptual'],
    subtopics: ['Poverty Line', 'Causes', 'Anti-poverty Measures'] },
  { id: 'sst9_food', title: 'Food Security in India', estimatedQCount: 2, importance: 'medium', tags: ['memory'],
    subtopics: ['Buffer Stock', 'Public Distribution System', 'Food Security'] },
];

export const eng9Topics: Topic[] = [
  { id: 'eng9_reading', title: 'Reading Comprehension', estimatedQCount: 5, importance: 'high', tags: ['conceptual'],
    subtopics: ['Factual Passages', 'Discursive Passages', 'Inference Questions'] },
  { id: 'eng9_grammar', title: 'Grammar', estimatedQCount: 6, importance: 'high', tags: ['conceptual'],
    subtopics: ['Tenses', 'Modals', 'Subject-Verb Agreement', 'Reported Speech', 'Determiners'] },
  { id: 'eng9_writing', title: 'Writing Skills', estimatedQCount: 4, importance: 'medium', tags: ['conceptual'],
    subtopics: ['Diary Entry', 'Story Writing', 'Descriptive Paragraph'] },
  { id: 'eng9_beehive_prose', title: 'Literature — Beehive (Prose)', estimatedQCount: 4, importance: 'high', tags: ['memory'],
    subtopics: ['Theme & Message', 'Character', 'Textual Questions'] },
  { id: 'eng9_beehive_poetry', title: 'Literature — Beehive (Poetry)', estimatedQCount: 3, importance: 'medium', tags: ['memory'],
    subtopics: ['Central Idea', 'Figures of Speech', 'Poetic Devices'] },
  { id: 'eng9_moments', title: 'Literature — Moments (Supplementary)', estimatedQCount: 3, importance: 'medium', tags: ['memory'],
    subtopics: ['Plot & Theme', 'Characters', 'Moral'] },
];

// ══════════════════════════════ CLASS 10 ═════════════════════════════════════

export const sci10Topics: Topic[] = [
  { id: 'sci10_reactions', title: 'Chemical Reactions and Equations', estimatedQCount: 5, importance: 'high', tags: ['conceptual'],
    subtopics: ['Types of Reactions', 'Balancing Equations', 'Oxidation & Reduction'] },
  { id: 'sci10_acids', title: 'Acids, Bases and Salts', estimatedQCount: 5, importance: 'high', tags: ['conceptual'],
    subtopics: ['pH Scale', 'Neutralisation', 'Common Salts'] },
  { id: 'sci10_metals', title: 'Metals and Non-metals', estimatedQCount: 5, importance: 'high', tags: ['memory', 'conceptual'],
    subtopics: ['Reactivity Series', 'Extraction of Metals', 'Corrosion'] },
  { id: 'sci10_carbon', title: 'Carbon and its Compounds', estimatedQCount: 6, importance: 'high', tags: ['conceptual'],
    subtopics: ['Covalent Bonding', 'Functional Groups', 'Soaps & Detergents'] },
  { id: 'sci10_life', title: 'Life Processes', estimatedQCount: 6, importance: 'high', tags: ['memory', 'conceptual'],
    subtopics: ['Nutrition', 'Respiration', 'Transportation', 'Excretion'] },
  { id: 'sci10_control', title: 'Control and Coordination', estimatedQCount: 4, importance: 'high', tags: ['memory'],
    subtopics: ['Nervous System', 'Reflex Action', 'Hormones'] },
  { id: 'sci10_reproduce', title: 'How do Organisms Reproduce?', estimatedQCount: 4, importance: 'high', tags: ['memory'],
    subtopics: ['Asexual Reproduction', 'Sexual Reproduction', 'Reproductive Health'] },
  { id: 'sci10_heredity', title: 'Heredity and Evolution', estimatedQCount: 4, importance: 'high', tags: ['conceptual'],
    subtopics: ["Mendel's Laws", 'Sex Determination', 'Evolution'] },
  { id: 'sci10_light', title: 'Light – Reflection and Refraction', estimatedQCount: 6, importance: 'high', tags: ['numerical', 'formula-heavy'],
    subtopics: ['Spherical Mirrors', 'Refraction & Lenses', 'Mirror & Lens Formula'] },
  { id: 'sci10_eye', title: 'The Human Eye and the Colourful World', estimatedQCount: 4, importance: 'medium', tags: ['conceptual'],
    subtopics: ['Defects of Vision', 'Dispersion', 'Scattering of Light'] },
  { id: 'sci10_electricity', title: 'Electricity', estimatedQCount: 6, importance: 'high', tags: ['numerical', 'formula-heavy'],
    subtopics: ["Ohm's Law", 'Resistance in Series/Parallel', 'Heating Effect'] },
  { id: 'sci10_magnetic', title: 'Magnetic Effects of Electric Current', estimatedQCount: 4, importance: 'medium', tags: ['conceptual'],
    subtopics: ['Magnetic Field', "Fleming's Rules", 'Motor & Generator'] },
  { id: 'sci10_environ', title: 'Our Environment', estimatedQCount: 3, importance: 'medium', tags: ['memory'],
    subtopics: ['Food Chain & Web', 'Ozone Depletion', 'Waste Management'] },
];

export const math10Topics: Topic[] = [
  { id: 'math10_real', title: 'Real Numbers', estimatedQCount: 4, importance: 'high', tags: ['conceptual'],
    subtopics: ["Euclid's Division Lemma", 'Fundamental Theorem of Arithmetic', 'Irrationality Proofs'] },
  { id: 'math10_poly', title: 'Polynomials', estimatedQCount: 4, importance: 'high', tags: ['formula-heavy'],
    subtopics: ['Zeroes of a Polynomial', 'Relationship between Zeroes & Coefficients'] },
  { id: 'math10_linear', title: 'Pair of Linear Equations in Two Variables', estimatedQCount: 5, importance: 'high', tags: ['numerical'],
    subtopics: ['Graphical Method', 'Substitution & Elimination', 'Cross Multiplication'] },
  { id: 'math10_quad', title: 'Quadratic Equations', estimatedQCount: 5, importance: 'high', tags: ['numerical', 'formula-heavy'],
    subtopics: ['Factorisation', 'Quadratic Formula', 'Nature of Roots'] },
  { id: 'math10_ap', title: 'Arithmetic Progressions', estimatedQCount: 4, importance: 'high', tags: ['formula-heavy', 'numerical'],
    subtopics: ['nth Term', 'Sum of n Terms', 'Applications'] },
  { id: 'math10_triangles', title: 'Triangles', estimatedQCount: 5, importance: 'high', tags: ['conceptual'],
    subtopics: ['Similarity Criteria', 'Basic Proportionality Theorem', 'Pythagoras Theorem'] },
  { id: 'math10_coord', title: 'Coordinate Geometry', estimatedQCount: 4, importance: 'high', tags: ['formula-heavy', 'numerical'],
    subtopics: ['Distance Formula', 'Section Formula', 'Area of Triangle'] },
  { id: 'math10_trig', title: 'Introduction to Trigonometry', estimatedQCount: 5, importance: 'high', tags: ['formula-heavy'],
    subtopics: ['Trigonometric Ratios', 'Identities', 'Specific Angles'] },
  { id: 'math10_trig_app', title: 'Some Applications of Trigonometry', estimatedQCount: 3, importance: 'medium', tags: ['numerical'],
    subtopics: ['Heights & Distances', 'Angle of Elevation/Depression'] },
  { id: 'math10_circles', title: 'Circles', estimatedQCount: 3, importance: 'medium', tags: ['conceptual'],
    subtopics: ['Tangent to a Circle', 'Number of Tangents'] },
  { id: 'math10_area', title: 'Areas Related to Circles', estimatedQCount: 3, importance: 'medium', tags: ['formula-heavy', 'numerical'],
    subtopics: ['Area of Sector & Segment', 'Perimeter'] },
  { id: 'math10_surface', title: 'Surface Areas and Volumes', estimatedQCount: 4, importance: 'high', tags: ['formula-heavy', 'numerical'],
    subtopics: ['Combination of Solids', 'Frustum of a Cone', 'Conversion of Solids'] },
  { id: 'math10_stats', title: 'Statistics', estimatedQCount: 3, importance: 'medium', tags: ['numerical'],
    subtopics: ['Mean of Grouped Data', 'Median & Mode', 'Cumulative Frequency'] },
  { id: 'math10_prob', title: 'Probability', estimatedQCount: 3, importance: 'medium', tags: ['numerical'],
    subtopics: ['Classical Probability', 'Sample Space', 'Simple Events'] },
];

export const sst10Topics: Topic[] = [
  // History — India and the Contemporary World II
  { id: 'sst10_europe', title: 'The Rise of Nationalism in Europe', estimatedQCount: 4, importance: 'high', tags: ['memory'],
    subtopics: ['French Revolution & Nationalism', 'Unification of Germany & Italy', 'Nationalism & Imperialism'] },
  { id: 'sst10_india_nat', title: 'Nationalism in India', estimatedQCount: 4, importance: 'high', tags: ['memory'],
    subtopics: ['Non-Cooperation Movement', 'Civil Disobedience', 'Sense of Collective Belonging'] },
  { id: 'sst10_global', title: 'The Making of a Global World', estimatedQCount: 3, importance: 'medium', tags: ['memory'],
    subtopics: ['Pre-modern Trade', 'Inter-war Economy', 'Globalisation'] },
  { id: 'sst10_industrial', title: 'The Age of Industrialisation', estimatedQCount: 3, importance: 'medium', tags: ['memory'],
    subtopics: ['Proto-industrialisation', 'Factory System', 'Industrial Growth in India'] },
  { id: 'sst10_print', title: 'Print Culture and the Modern World', estimatedQCount: 2, importance: 'low', tags: ['memory'],
    subtopics: ['Print Revolution', 'Print & Reforms', 'Censorship'] },
  // Geography — Contemporary India II
  { id: 'sst10_resources', title: 'Resources and Development', estimatedQCount: 3, importance: 'high', tags: ['conceptual'],
    subtopics: ['Types of Resources', 'Land & Soil', 'Resource Planning'] },
  { id: 'sst10_forest', title: 'Forest and Wildlife Resources', estimatedQCount: 2, importance: 'medium', tags: ['memory'],
    subtopics: ['Biodiversity', 'Conservation', 'Community & Forests'] },
  { id: 'sst10_water', title: 'Water Resources', estimatedQCount: 3, importance: 'medium', tags: ['memory'],
    subtopics: ['Scarcity', 'Dams', 'Rainwater Harvesting'] },
  { id: 'sst10_agri', title: 'Agriculture', estimatedQCount: 3, importance: 'medium', tags: ['memory'],
    subtopics: ['Cropping Patterns', 'Major Crops', 'Food Security'] },
  { id: 'sst10_minerals', title: 'Minerals and Energy Resources', estimatedQCount: 3, importance: 'medium', tags: ['memory'],
    subtopics: ['Types of Minerals', 'Conventional & Non-conventional Energy'] },
  { id: 'sst10_manufacturing', title: 'Manufacturing Industries', estimatedQCount: 3, importance: 'medium', tags: ['memory'],
    subtopics: ['Classification of Industries', 'Industrial Location', 'Pollution'] },
  { id: 'sst10_lifelines', title: 'Lifelines of National Economy', estimatedQCount: 2, importance: 'medium', tags: ['memory'],
    subtopics: ['Transport', 'Communication', 'Trade'] },
  // Civics — Democratic Politics II
  { id: 'sst10_power', title: 'Power Sharing', estimatedQCount: 3, importance: 'high', tags: ['conceptual'],
    subtopics: ['Forms of Power Sharing', 'Belgium & Sri Lanka'] },
  { id: 'sst10_federalism', title: 'Federalism', estimatedQCount: 3, importance: 'high', tags: ['conceptual'],
    subtopics: ['Features of Federalism', 'Decentralisation in India'] },
  { id: 'sst10_gender', title: 'Gender, Religion and Caste', estimatedQCount: 2, importance: 'medium', tags: ['conceptual'],
    subtopics: ['Gender & Politics', 'Communalism', 'Caste in Politics'] },
  { id: 'sst10_parties', title: 'Political Parties', estimatedQCount: 2, importance: 'medium', tags: ['memory'],
    subtopics: ['Functions', 'National & State Parties', 'Challenges'] },
  { id: 'sst10_outcomes', title: 'Outcomes of Democracy', estimatedQCount: 2, importance: 'medium', tags: ['conceptual'],
    subtopics: ['Accountability', 'Economic Outcomes', 'Equality'] },
  // Economics — Understanding Economic Development
  { id: 'sst10_development', title: 'Development', estimatedQCount: 3, importance: 'high', tags: ['conceptual'],
    subtopics: ['Income & Other Goals', 'HDI', 'Sustainability'] },
  { id: 'sst10_sectors', title: 'Sectors of the Indian Economy', estimatedQCount: 3, importance: 'high', tags: ['conceptual'],
    subtopics: ['Primary/Secondary/Tertiary', 'Organised & Unorganised', 'GDP'] },
  { id: 'sst10_money', title: 'Money and Credit', estimatedQCount: 3, importance: 'medium', tags: ['conceptual'],
    subtopics: ['Functions of Money', 'Formal & Informal Credit', 'Self-Help Groups'] },
  { id: 'sst10_globalisation', title: 'Globalisation and the Indian Economy', estimatedQCount: 2, importance: 'medium', tags: ['conceptual'],
    subtopics: ['MNCs', 'Liberalisation', 'Impact'] },
  { id: 'sst10_consumer', title: 'Consumer Rights', estimatedQCount: 2, importance: 'low', tags: ['memory'],
    subtopics: ['Consumer Exploitation', 'Consumer Rights', 'COPRA'] },
];

export const eng10Topics: Topic[] = [
  { id: 'eng10_reading', title: 'Reading Comprehension', estimatedQCount: 5, importance: 'high', tags: ['conceptual'],
    subtopics: ['Factual Passages', 'Discursive Passages', 'Inference Questions'] },
  { id: 'eng10_grammar', title: 'Grammar', estimatedQCount: 6, importance: 'high', tags: ['conceptual'],
    subtopics: ['Tenses', 'Modals', 'Reported Speech', 'Subject-Verb Agreement', 'Determiners'] },
  { id: 'eng10_writing', title: 'Writing Skills', estimatedQCount: 4, importance: 'medium', tags: ['conceptual'],
    subtopics: ['Formal Letter', 'Analytical Paragraph', 'Email'] },
  { id: 'eng10_ff_prose', title: 'Literature — First Flight (Prose)', estimatedQCount: 4, importance: 'high', tags: ['memory'],
    subtopics: ['Theme & Message', 'Character', 'Textual Questions'] },
  { id: 'eng10_ff_poetry', title: 'Literature — First Flight (Poetry)', estimatedQCount: 3, importance: 'medium', tags: ['memory'],
    subtopics: ['Central Idea', 'Figures of Speech', 'Poetic Devices'] },
  { id: 'eng10_footprints', title: 'Literature — Footprints Without Feet', estimatedQCount: 3, importance: 'medium', tags: ['memory'],
    subtopics: ['Plot & Theme', 'Characters', 'Moral'] },
];

// ══════════════════════════════ CLASS 11 ═════════════════════════════════════

export const phy11Topics: Topic[] = [
  { id: 'phy11_units', title: 'Units and Measurements', estimatedQCount: 4, importance: 'high', tags: ['numerical', 'conceptual'],
    subtopics: ['SI Units', 'Dimensional Analysis', 'Significant Figures', 'Errors'] },
  { id: 'phy11_kinematics', title: 'Motion in a Straight Line', estimatedQCount: 5, importance: 'high', tags: ['numerical', 'formula-heavy'],
    subtopics: ['Velocity & Acceleration', 'Equations of Motion', 'Relative Velocity'] },
  { id: 'phy11_plane', title: 'Motion in a Plane', estimatedQCount: 5, importance: 'high', tags: ['numerical', 'formula-heavy'],
    subtopics: ['Vectors', 'Projectile Motion', 'Circular Motion'] },
  { id: 'phy11_laws', title: 'Laws of Motion', estimatedQCount: 6, importance: 'high', tags: ['numerical', 'conceptual'],
    subtopics: ["Newton's Laws", 'Friction', 'Circular Dynamics'] },
  { id: 'phy11_work', title: 'Work, Energy and Power', estimatedQCount: 5, importance: 'high', tags: ['numerical', 'formula-heavy'],
    subtopics: ['Work-Energy Theorem', 'Conservation of Energy', 'Collisions'] },
  { id: 'phy11_rotation', title: 'System of Particles and Rotational Motion', estimatedQCount: 5, importance: 'high', tags: ['numerical', 'formula-heavy'],
    subtopics: ['Centre of Mass', 'Torque', 'Moment of Inertia', 'Angular Momentum'] },
  { id: 'phy11_gravitation', title: 'Gravitation', estimatedQCount: 4, importance: 'medium', tags: ['numerical', 'formula-heavy'],
    subtopics: ["Kepler's Laws", 'Gravitational Potential', 'Escape & Orbital Velocity'] },
  { id: 'phy11_solids', title: 'Mechanical Properties of Solids', estimatedQCount: 3, importance: 'medium', tags: ['conceptual', 'formula-heavy'],
    subtopics: ['Stress & Strain', "Young's Modulus", 'Elastic Behaviour'] },
  { id: 'phy11_fluids', title: 'Mechanical Properties of Fluids', estimatedQCount: 4, importance: 'medium', tags: ['conceptual', 'numerical'],
    subtopics: ["Pascal's Law", "Bernoulli's Principle", 'Viscosity', 'Surface Tension'] },
  { id: 'phy11_thermal', title: 'Thermal Properties of Matter', estimatedQCount: 4, importance: 'medium', tags: ['conceptual', 'numerical'],
    subtopics: ['Thermal Expansion', 'Calorimetry', 'Heat Transfer'] },
  { id: 'phy11_thermo', title: 'Thermodynamics', estimatedQCount: 5, importance: 'high', tags: ['conceptual', 'formula-heavy'],
    subtopics: ['Laws of Thermodynamics', 'Heat Engines', 'Carnot Cycle'] },
  { id: 'phy11_kinetic', title: 'Kinetic Theory', estimatedQCount: 3, importance: 'medium', tags: ['conceptual'],
    subtopics: ['Ideal Gas Equation', 'Degrees of Freedom', 'Mean Free Path'] },
  { id: 'phy11_oscillations', title: 'Oscillations', estimatedQCount: 4, importance: 'high', tags: ['formula-heavy', 'numerical'],
    subtopics: ['SHM', 'Simple Pendulum', 'Energy in SHM'] },
  { id: 'phy11_waves', title: 'Waves', estimatedQCount: 4, importance: 'high', tags: ['conceptual', 'numerical'],
    subtopics: ['Wave Motion', 'Superposition', 'Standing Waves', 'Doppler Effect'] },
];

export const chem11Topics: Topic[] = [
  { id: 'chem11_basic', title: 'Some Basic Concepts of Chemistry', estimatedQCount: 4, importance: 'high', tags: ['numerical'],
    subtopics: ['Mole Concept', 'Stoichiometry', 'Concentration Terms'] },
  { id: 'chem11_atom', title: 'Structure of Atom', estimatedQCount: 5, importance: 'high', tags: ['conceptual'],
    subtopics: ['Bohr Model', 'Quantum Numbers', 'Electronic Configuration'] },
  { id: 'chem11_periodic', title: 'Classification of Elements & Periodicity', estimatedQCount: 4, importance: 'high', tags: ['memory', 'conceptual'],
    subtopics: ['Periodic Trends', 'Ionization Enthalpy', 'Electronegativity'] },
  { id: 'chem11_bonding', title: 'Chemical Bonding and Molecular Structure', estimatedQCount: 5, importance: 'high', tags: ['conceptual'],
    subtopics: ['VSEPR Theory', 'Hybridisation', 'Molecular Orbital Theory'] },
  { id: 'chem11_states', title: 'States of Matter', estimatedQCount: 3, importance: 'medium', tags: ['numerical', 'formula-heavy'],
    subtopics: ['Gas Laws', 'Ideal Gas Equation', 'Kinetic Molecular Theory'] },
  { id: 'chem11_thermo', title: 'Thermodynamics', estimatedQCount: 4, importance: 'high', tags: ['numerical', 'formula-heavy'],
    subtopics: ['Enthalpy', "Hess's Law", 'Entropy & Gibbs Energy'] },
  { id: 'chem11_equilibrium', title: 'Equilibrium', estimatedQCount: 5, importance: 'high', tags: ['numerical', 'conceptual'],
    subtopics: ['Le Chatelier Principle', 'Ionic Equilibrium', 'pH & Buffers'] },
  { id: 'chem11_redox', title: 'Redox Reactions', estimatedQCount: 3, importance: 'medium', tags: ['conceptual'],
    subtopics: ['Oxidation Number', 'Balancing Redox', 'Electrode Potential'] },
  { id: 'chem11_organic', title: 'Organic Chemistry — Basic Principles', estimatedQCount: 4, importance: 'high', tags: ['conceptual'],
    subtopics: ['IUPAC Nomenclature', 'Isomerism', 'Electronic Effects'] },
  { id: 'chem11_hydrocarbons', title: 'Hydrocarbons', estimatedQCount: 4, importance: 'high', tags: ['memory', 'conceptual'],
    subtopics: ['Alkanes, Alkenes, Alkynes', 'Aromatic Hydrocarbons', 'Reactions'] },
];

export const math11Topics: Topic[] = [
  { id: 'math11_sets', title: 'Sets', estimatedQCount: 3, importance: 'high', tags: ['conceptual'],
    subtopics: ['Set Operations', 'Venn Diagrams', 'Subsets'] },
  { id: 'math11_relations', title: 'Relations and Functions', estimatedQCount: 4, importance: 'high', tags: ['conceptual'],
    subtopics: ['Types of Relations', 'Domain & Range', 'Types of Functions'] },
  { id: 'math11_trig', title: 'Trigonometric Functions', estimatedQCount: 5, importance: 'high', tags: ['formula-heavy'],
    subtopics: ['Trigonometric Identities', 'General Solutions', 'Properties of Triangles'] },
  { id: 'math11_complex', title: 'Complex Numbers and Quadratic Equations', estimatedQCount: 4, importance: 'high', tags: ['formula-heavy', 'numerical'],
    subtopics: ['Argand Plane', 'Modulus & Argument', 'Quadratic with Complex Roots'] },
  { id: 'math11_inequalities', title: 'Linear Inequalities', estimatedQCount: 3, importance: 'medium', tags: ['numerical'],
    subtopics: ['Algebraic Solutions', 'Graphical Solutions', 'Systems of Inequalities'] },
  { id: 'math11_pnc', title: 'Permutations and Combinations', estimatedQCount: 4, importance: 'high', tags: ['numerical'],
    subtopics: ['Fundamental Principle', 'Permutations', 'Combinations'] },
  { id: 'math11_binomial', title: 'Binomial Theorem', estimatedQCount: 3, importance: 'medium', tags: ['formula-heavy'],
    subtopics: ['General & Middle Term', 'Properties of Coefficients'] },
  { id: 'math11_sequences', title: 'Sequences and Series', estimatedQCount: 4, importance: 'high', tags: ['formula-heavy', 'numerical'],
    subtopics: ['AP & GP', 'Sum to n Terms', 'Special Series'] },
  { id: 'math11_lines', title: 'Straight Lines', estimatedQCount: 4, importance: 'high', tags: ['formula-heavy'],
    subtopics: ['Slope', 'Forms of a Line', 'Distance of a Point'] },
  { id: 'math11_conic', title: 'Conic Sections', estimatedQCount: 4, importance: 'high', tags: ['formula-heavy'],
    subtopics: ['Circle', 'Parabola', 'Ellipse & Hyperbola'] },
  { id: 'math11_3d', title: 'Introduction to Three Dimensional Geometry', estimatedQCount: 2, importance: 'medium', tags: ['formula-heavy'],
    subtopics: ['Coordinates in Space', 'Distance Formula', 'Section Formula'] },
  { id: 'math11_limits', title: 'Limits and Derivatives', estimatedQCount: 5, importance: 'high', tags: ['formula-heavy', 'numerical'],
    subtopics: ['Limits', 'First Principle Derivative', 'Rules of Differentiation'] },
  { id: 'math11_stats', title: 'Statistics', estimatedQCount: 3, importance: 'medium', tags: ['numerical'],
    subtopics: ['Measures of Dispersion', 'Variance & Standard Deviation'] },
  { id: 'math11_prob', title: 'Probability', estimatedQCount: 3, importance: 'medium', tags: ['numerical'],
    subtopics: ['Random Experiments', 'Events', 'Axiomatic Probability'] },
];

export const bio11Topics: Topic[] = [
  { id: 'bio11_living', title: 'The Living World', estimatedQCount: 3, importance: 'medium', tags: ['memory'],
    subtopics: ['Taxonomy', 'Taxonomic Categories', 'Nomenclature'] },
  { id: 'bio11_classification', title: 'Biological Classification', estimatedQCount: 4, importance: 'high', tags: ['memory'],
    subtopics: ['Five Kingdoms', 'Monera & Protista', 'Fungi'] },
  { id: 'bio11_plant_kingdom', title: 'Plant Kingdom', estimatedQCount: 3, importance: 'medium', tags: ['memory'],
    subtopics: ['Algae & Bryophytes', 'Pteridophytes', 'Gymnosperms & Angiosperms'] },
  { id: 'bio11_animal_kingdom', title: 'Animal Kingdom', estimatedQCount: 4, importance: 'high', tags: ['memory'],
    subtopics: ['Basis of Classification', 'Non-chordates', 'Chordates'] },
  { id: 'bio11_morphology', title: 'Morphology of Flowering Plants', estimatedQCount: 3, importance: 'medium', tags: ['memory'],
    subtopics: ['Root, Stem, Leaf', 'Flower & Inflorescence', 'Families'] },
  { id: 'bio11_anatomy', title: 'Anatomy of Flowering Plants', estimatedQCount: 3, importance: 'medium', tags: ['memory'],
    subtopics: ['Tissues', 'Tissue Systems', 'Secondary Growth'] },
  { id: 'bio11_animal_org', title: 'Structural Organisation in Animals', estimatedQCount: 2, importance: 'low', tags: ['memory'],
    subtopics: ['Animal Tissues', 'Organ Systems'] },
  { id: 'bio11_cell', title: 'Cell: The Unit of Life', estimatedQCount: 5, importance: 'high', tags: ['memory', 'conceptual'],
    subtopics: ['Cell Organelles', 'Prokaryotic vs Eukaryotic', 'Cell Membrane'] },
  { id: 'bio11_biomolecules', title: 'Biomolecules', estimatedQCount: 4, importance: 'high', tags: ['conceptual'],
    subtopics: ['Carbohydrates & Proteins', 'Enzymes', 'Nucleic Acids'] },
  { id: 'bio11_cell_cycle', title: 'Cell Cycle and Cell Division', estimatedQCount: 4, importance: 'high', tags: ['conceptual'],
    subtopics: ['Mitosis', 'Meiosis', 'Significance'] },
  { id: 'bio11_photosynthesis', title: 'Photosynthesis in Higher Plants', estimatedQCount: 4, importance: 'high', tags: ['conceptual'],
    subtopics: ['Light Reaction', 'Calvin Cycle', 'C4 Pathway'] },
  { id: 'bio11_respiration', title: 'Respiration in Plants', estimatedQCount: 3, importance: 'medium', tags: ['conceptual'],
    subtopics: ['Glycolysis', 'Krebs Cycle', 'Electron Transport'] },
  { id: 'bio11_growth', title: 'Plant Growth and Development', estimatedQCount: 2, importance: 'low', tags: ['memory'],
    subtopics: ['Growth Phases', 'Plant Hormones', 'Photoperiodism'] },
  { id: 'bio11_breathing', title: 'Breathing and Exchange of Gases', estimatedQCount: 3, importance: 'medium', tags: ['memory'],
    subtopics: ['Respiratory Organs', 'Transport of Gases', 'Regulation'] },
  { id: 'bio11_circulation', title: 'Body Fluids and Circulation', estimatedQCount: 3, importance: 'medium', tags: ['memory'],
    subtopics: ['Blood & Lymph', 'Human Heart', 'Cardiac Cycle'] },
  { id: 'bio11_excretion', title: 'Excretory Products and their Elimination', estimatedQCount: 3, importance: 'medium', tags: ['memory'],
    subtopics: ['Human Excretory System', 'Urine Formation', 'Regulation'] },
  { id: 'bio11_locomotion', title: 'Locomotion and Movement', estimatedQCount: 2, importance: 'low', tags: ['memory'],
    subtopics: ['Muscles', 'Skeletal System', 'Joints'] },
  { id: 'bio11_neural', title: 'Neural Control and Coordination', estimatedQCount: 3, importance: 'medium', tags: ['memory'],
    subtopics: ['Neuron & Nerve Impulse', 'Central Nervous System', 'Reflex Action'] },
  { id: 'bio11_chemical', title: 'Chemical Coordination and Integration', estimatedQCount: 3, importance: 'medium', tags: ['memory'],
    subtopics: ['Endocrine Glands', 'Hormones', 'Mechanism of Hormone Action'] },
];

export const eng11Topics: Topic[] = [
  { id: 'eng11_reading', title: 'Reading Comprehension', estimatedQCount: 5, importance: 'high', tags: ['conceptual'],
    subtopics: ['Factual & Discursive Passages', 'Note Making', 'Inference'] },
  { id: 'eng11_grammar', title: 'Grammar', estimatedQCount: 5, importance: 'high', tags: ['conceptual'],
    subtopics: ['Tenses', 'Determiners', 'Reported Speech', 'Voice'] },
  { id: 'eng11_writing', title: 'Writing Skills', estimatedQCount: 4, importance: 'medium', tags: ['conceptual'],
    subtopics: ['Notice & Poster', 'Letter Writing', 'Article Writing'] },
  { id: 'eng11_hornbill_prose', title: 'Literature — Hornbill (Prose)', estimatedQCount: 4, importance: 'high', tags: ['memory'],
    subtopics: ['Theme & Message', 'Character', 'Textual Questions'] },
  { id: 'eng11_hornbill_poetry', title: 'Literature — Hornbill (Poetry)', estimatedQCount: 3, importance: 'medium', tags: ['memory'],
    subtopics: ['Central Idea', 'Poetic Devices', 'Figures of Speech'] },
  { id: 'eng11_snapshots', title: 'Literature — Snapshots', estimatedQCount: 3, importance: 'medium', tags: ['memory'],
    subtopics: ['Plot & Theme', 'Characters', 'Moral'] },
];

// ══════════════════════════════ CLASS 12 ═════════════════════════════════════

export const phy12Topics: Topic[] = [
  { id: 'phy12_charges', title: 'Electric Charges and Fields', estimatedQCount: 5, importance: 'high', tags: ['numerical', 'formula-heavy'],
    subtopics: ["Coulomb's Law", 'Electric Field', "Gauss's Law"] },
  { id: 'phy12_potential', title: 'Electrostatic Potential and Capacitance', estimatedQCount: 5, importance: 'high', tags: ['numerical', 'formula-heavy'],
    subtopics: ['Potential & Equipotential', 'Capacitors', 'Energy Stored'] },
  { id: 'phy12_current', title: 'Current Electricity', estimatedQCount: 5, importance: 'high', tags: ['numerical'],
    subtopics: ["Ohm's Law", "Kirchhoff's Laws", 'Wheatstone Bridge'] },
  { id: 'phy12_magnetism', title: 'Moving Charges and Magnetism', estimatedQCount: 4, importance: 'high', tags: ['numerical', 'formula-heavy'],
    subtopics: ['Biot-Savart Law', "Ampere's Law", 'Force on a Conductor'] },
  { id: 'phy12_magnet_matter', title: 'Magnetism and Matter', estimatedQCount: 3, importance: 'medium', tags: ['conceptual'],
    subtopics: ['Bar Magnet', 'Magnetic Properties', 'Earth Magnetism'] },
  { id: 'phy12_emi', title: 'Electromagnetic Induction', estimatedQCount: 4, importance: 'high', tags: ['conceptual', 'formula-heavy'],
    subtopics: ["Faraday's Law", "Lenz's Law", 'Self & Mutual Inductance'] },
  { id: 'phy12_ac', title: 'Alternating Current', estimatedQCount: 4, importance: 'high', tags: ['numerical', 'formula-heavy'],
    subtopics: ['AC Circuits', 'Resonance', 'Transformers'] },
  { id: 'phy12_em_waves', title: 'Electromagnetic Waves', estimatedQCount: 2, importance: 'medium', tags: ['conceptual'],
    subtopics: ['Displacement Current', 'EM Spectrum', 'Properties'] },
  { id: 'phy12_ray_optics', title: 'Ray Optics and Optical Instruments', estimatedQCount: 5, importance: 'high', tags: ['numerical', 'formula-heavy'],
    subtopics: ['Reflection & Refraction', 'Lenses', 'Optical Instruments'] },
  { id: 'phy12_wave_optics', title: 'Wave Optics', estimatedQCount: 4, importance: 'high', tags: ['conceptual', 'numerical'],
    subtopics: ["Huygens' Principle", 'Interference', 'Diffraction'] },
  { id: 'phy12_dual', title: 'Dual Nature of Radiation and Matter', estimatedQCount: 3, importance: 'high', tags: ['conceptual', 'numerical'],
    subtopics: ['Photoelectric Effect', 'de Broglie Wavelength'] },
  { id: 'phy12_atoms', title: 'Atoms', estimatedQCount: 3, importance: 'medium', tags: ['conceptual'],
    subtopics: ['Rutherford Model', 'Bohr Model', 'Hydrogen Spectrum'] },
  { id: 'phy12_nuclei', title: 'Nuclei', estimatedQCount: 3, importance: 'medium', tags: ['conceptual', 'numerical'],
    subtopics: ['Mass-Energy', 'Radioactivity', 'Fission & Fusion'] },
  { id: 'phy12_semiconductor', title: 'Semiconductor Electronics', estimatedQCount: 4, importance: 'high', tags: ['conceptual'],
    subtopics: ['p-n Junction', 'Diodes & Rectifiers', 'Logic Gates'] },
];

export const chem12Topics: Topic[] = [
  { id: 'chem12_solutions', title: 'Solutions', estimatedQCount: 4, importance: 'high', tags: ['numerical'],
    subtopics: ['Concentration', "Raoult's Law", 'Colligative Properties'] },
  { id: 'chem12_electro', title: 'Electrochemistry', estimatedQCount: 5, importance: 'high', tags: ['numerical', 'formula-heavy'],
    subtopics: ['Nernst Equation', 'Conductance', 'Electrolysis'] },
  { id: 'chem12_kinetics', title: 'Chemical Kinetics', estimatedQCount: 4, importance: 'high', tags: ['numerical'],
    subtopics: ['Rate of Reaction', 'Order & Molecularity', 'Arrhenius Equation'] },
  { id: 'chem12_dblock', title: 'The d- and f-Block Elements', estimatedQCount: 4, importance: 'high', tags: ['memory'],
    subtopics: ['Transition Elements', 'Lanthanoids & Actinoids', 'Properties'] },
  { id: 'chem12_coordination', title: 'Coordination Compounds', estimatedQCount: 4, importance: 'high', tags: ['conceptual'],
    subtopics: ['Nomenclature', "Werner's Theory", 'Crystal Field Theory'] },
  { id: 'chem12_haloalkanes', title: 'Haloalkanes and Haloarenes', estimatedQCount: 4, importance: 'high', tags: ['conceptual'],
    subtopics: ['Nomenclature', 'SN1 & SN2', 'Reactions'] },
  { id: 'chem12_alcohols', title: 'Alcohols, Phenols and Ethers', estimatedQCount: 4, importance: 'high', tags: ['conceptual'],
    subtopics: ['Preparation', 'Properties', 'Reactions'] },
  { id: 'chem12_aldehydes', title: 'Aldehydes, Ketones and Carboxylic Acids', estimatedQCount: 5, importance: 'high', tags: ['conceptual'],
    subtopics: ['Nucleophilic Addition', 'Acidity of Carboxylic Acids', 'Named Reactions'] },
  { id: 'chem12_amines', title: 'Amines', estimatedQCount: 3, importance: 'medium', tags: ['conceptual'],
    subtopics: ['Classification', 'Basicity', 'Diazonium Salts'] },
  { id: 'chem12_biomolecules', title: 'Biomolecules', estimatedQCount: 3, importance: 'medium', tags: ['memory'],
    subtopics: ['Carbohydrates', 'Proteins & Enzymes', 'Nucleic Acids & Vitamins'] },
];

export const math12Topics: Topic[] = [
  { id: 'math12_relations', title: 'Relations and Functions', estimatedQCount: 4, importance: 'high', tags: ['conceptual'],
    subtopics: ['Types of Relations', 'One-One & Onto', 'Composition & Inverse'] },
  { id: 'math12_inverse_trig', title: 'Inverse Trigonometric Functions', estimatedQCount: 3, importance: 'medium', tags: ['formula-heavy'],
    subtopics: ['Principal Values', 'Properties', 'Identities'] },
  { id: 'math12_matrices', title: 'Matrices', estimatedQCount: 4, importance: 'high', tags: ['numerical'],
    subtopics: ['Operations', 'Transpose & Symmetric', 'Inverse by Elementary Operations'] },
  { id: 'math12_determinants', title: 'Determinants', estimatedQCount: 4, importance: 'high', tags: ['numerical', 'formula-heavy'],
    subtopics: ['Properties', 'Adjoint & Inverse', "Cramer's Rule"] },
  { id: 'math12_continuity', title: 'Continuity and Differentiability', estimatedQCount: 5, importance: 'high', tags: ['formula-heavy', 'numerical'],
    subtopics: ['Continuity', 'Chain Rule', 'Logarithmic & Implicit Differentiation'] },
  { id: 'math12_aod', title: 'Application of Derivatives', estimatedQCount: 5, importance: 'high', tags: ['numerical', 'formula-heavy'],
    subtopics: ['Rate of Change', 'Increasing/Decreasing', 'Maxima & Minima'] },
  { id: 'math12_integrals', title: 'Integrals', estimatedQCount: 6, importance: 'high', tags: ['formula-heavy', 'numerical'],
    subtopics: ['Methods of Integration', 'Definite Integrals', 'Properties'] },
  { id: 'math12_aoi', title: 'Application of Integrals', estimatedQCount: 3, importance: 'medium', tags: ['numerical'],
    subtopics: ['Area Under Curves', 'Area Between Curves'] },
  { id: 'math12_diff_eq', title: 'Differential Equations', estimatedQCount: 4, importance: 'high', tags: ['formula-heavy'],
    subtopics: ['Order & Degree', 'Variable Separable', 'Linear Differential Equations'] },
  { id: 'math12_vectors', title: 'Vector Algebra', estimatedQCount: 4, importance: 'high', tags: ['formula-heavy', 'numerical'],
    subtopics: ['Types of Vectors', 'Dot Product', 'Cross Product'] },
  { id: 'math12_3d', title: 'Three Dimensional Geometry', estimatedQCount: 4, importance: 'high', tags: ['formula-heavy'],
    subtopics: ['Direction Cosines', 'Line in Space', 'Plane'] },
  { id: 'math12_lpp', title: 'Linear Programming', estimatedQCount: 3, importance: 'medium', tags: ['numerical', 'graph-reading'],
    subtopics: ['Formulation', 'Graphical Method', 'Feasible Region'] },
  { id: 'math12_prob', title: 'Probability', estimatedQCount: 5, importance: 'high', tags: ['numerical'],
    subtopics: ['Conditional Probability', 'Bayes Theorem', 'Random Variables'] },
];

export const bio12Topics: Topic[] = [
  { id: 'bio12_sexual_plant', title: 'Sexual Reproduction in Flowering Plants', estimatedQCount: 4, importance: 'high', tags: ['memory', 'conceptual'],
    subtopics: ['Flower Structure', 'Pollination', 'Double Fertilisation'] },
  { id: 'bio12_human_repro', title: 'Human Reproduction', estimatedQCount: 4, importance: 'high', tags: ['memory'],
    subtopics: ['Reproductive Systems', 'Gametogenesis', 'Menstrual Cycle'] },
  { id: 'bio12_repro_health', title: 'Reproductive Health', estimatedQCount: 3, importance: 'medium', tags: ['memory'],
    subtopics: ['Birth Control', 'Infertility', 'STDs'] },
  { id: 'bio12_inheritance', title: 'Principles of Inheritance and Variation', estimatedQCount: 5, importance: 'high', tags: ['conceptual'],
    subtopics: ["Mendel's Laws", 'Linkage & Recombination', 'Genetic Disorders'] },
  { id: 'bio12_molecular', title: 'Molecular Basis of Inheritance', estimatedQCount: 5, importance: 'high', tags: ['conceptual'],
    subtopics: ['DNA Structure', 'Replication', 'Transcription & Translation'] },
  { id: 'bio12_evolution', title: 'Evolution', estimatedQCount: 4, importance: 'high', tags: ['conceptual'],
    subtopics: ['Origin of Life', 'Theories of Evolution', 'Hardy-Weinberg Principle'] },
  { id: 'bio12_health', title: 'Human Health and Disease', estimatedQCount: 4, importance: 'high', tags: ['memory'],
    subtopics: ['Immunity', 'Pathogens & Diseases', 'AIDS & Cancer'] },
  { id: 'bio12_microbes', title: 'Microbes in Human Welfare', estimatedQCount: 3, importance: 'medium', tags: ['memory'],
    subtopics: ['Microbes in Food', 'Industrial Products', 'Sewage Treatment'] },
  { id: 'bio12_biotech_prin', title: 'Biotechnology: Principles and Processes', estimatedQCount: 4, importance: 'high', tags: ['conceptual'],
    subtopics: ['Recombinant DNA', 'Tools of Biotechnology', 'PCR & Cloning'] },
  { id: 'bio12_biotech_app', title: 'Biotechnology and its Applications', estimatedQCount: 3, importance: 'medium', tags: ['memory'],
    subtopics: ['GM Crops', 'Gene Therapy', 'Transgenic Animals'] },
  { id: 'bio12_organisms', title: 'Organisms and Populations', estimatedQCount: 3, importance: 'medium', tags: ['conceptual'],
    subtopics: ['Adaptations', 'Population Growth', 'Interactions'] },
  { id: 'bio12_ecosystem', title: 'Ecosystem', estimatedQCount: 3, importance: 'medium', tags: ['conceptual'],
    subtopics: ['Energy Flow', 'Ecological Pyramids', 'Nutrient Cycling'] },
  { id: 'bio12_biodiversity', title: 'Biodiversity and Conservation', estimatedQCount: 3, importance: 'medium', tags: ['memory'],
    subtopics: ['Levels of Biodiversity', 'Loss of Biodiversity', 'Conservation'] },
];

export const eng12Topics: Topic[] = [
  { id: 'eng12_reading', title: 'Reading Comprehension', estimatedQCount: 5, importance: 'high', tags: ['conceptual'],
    subtopics: ['Factual & Discursive Passages', 'Note Making', 'Inference'] },
  { id: 'eng12_grammar', title: 'Grammar', estimatedQCount: 5, importance: 'high', tags: ['conceptual'],
    subtopics: ['Tenses', 'Reported Speech', 'Determiners', 'Voice'] },
  { id: 'eng12_writing', title: 'Writing Skills', estimatedQCount: 4, importance: 'medium', tags: ['conceptual'],
    subtopics: ['Notice & Advertisement', 'Letter Writing', 'Article & Report'] },
  { id: 'eng12_flamingo_prose', title: 'Literature — Flamingo (Prose)', estimatedQCount: 4, importance: 'high', tags: ['memory'],
    subtopics: ['Theme & Message', 'Character', 'Textual Questions'] },
  { id: 'eng12_flamingo_poetry', title: 'Literature — Flamingo (Poetry)', estimatedQCount: 3, importance: 'medium', tags: ['memory'],
    subtopics: ['Central Idea', 'Poetic Devices', 'Figures of Speech'] },
  { id: 'eng12_vistas', title: 'Literature — Vistas', estimatedQCount: 3, importance: 'medium', tags: ['memory'],
    subtopics: ['Plot & Theme', 'Characters', 'Moral'] },
];

// ─── Registry — section id → chapters ─────────────────────────────────────────
export const schoolingTopicMap: Record<string, Topic[]> = {
  // Class 9
  sci9: sci9Topics, math9: math9Topics, sst9: sst9Topics, eng9: eng9Topics,
  // Class 10
  sci10: sci10Topics, math10: math10Topics, sst10: sst10Topics, eng10: eng10Topics,
  // Class 11
  phy11: phy11Topics, chem11: chem11Topics, math11: math11Topics, bio11: bio11Topics, eng11: eng11Topics,
  // Class 12
  phy12: phy12Topics, chem12: chem12Topics, math12: math12Topics, bio12: bio12Topics, eng12: eng12Topics,
};
