export type BranchConfig = {
  id: string;
  name: string;
  shortName: string;
  color: string;
  bgColor: string;
  icon: string; // Ionicons name
  generalTip: string;          // overall study strategy for this branch
  coreSubjects: string[];      // top 3–4 highest-yield subjects — shown as UI chips
  allCoreSubjects: string[];   // full subject list (GATE official sections + PSU-specific additions)
};

export const BRANCHES: BranchConfig[] = [
  {
    id: 'mechanical',
    name: 'Mechanical Engineering',
    shortName: 'ME',
    color: '#F57C00',
    bgColor: '#FFF3E0',
    icon: 'settings',
    generalTip: 'Thermodynamics and Fluid Mechanics are king across all PSUs — nail formulas before moving to Theory of Machines and Manufacturing.',
    coreSubjects: ['Thermodynamics', 'Fluid Mechanics', 'Strength of Materials', 'Manufacturing Technology'],
    allCoreSubjects: [
      'Engineering Mechanics',
      'Strength of Materials',
      'Theory of Machines',
      'Machine Design',
      'Thermodynamics',
      'Fluid Mechanics',
      'Heat Transfer',
      'Engineering Materials',
      'Manufacturing Technology',
      'Industrial Engineering',
      'Power Plant Engineering',
    ],
  },
  {
    id: 'electrical',
    name: 'Electrical Engineering',
    shortName: 'EE',
    color: '#1976D2',
    bgColor: '#E3F2FD',
    icon: 'flash',
    generalTip: 'Electrical Machines + Power Systems together = ~40% in every EE exam. Control Systems and Power Electronics are the next priority.',
    coreSubjects: ['Electrical Machines', 'Power Systems', 'Control Systems', 'Power Electronics'],
    allCoreSubjects: [
      'Electric Circuits',
      'Electromagnetic Fields',
      'Signals & Systems',
      'Electrical Machines',
      'Power Systems',
      'Control Systems',
      'Electrical & Electronic Measurements',
      'Analog & Digital Electronics',
      'Power Electronics',
      'HVDC & FACTS Technology',
      'Renewable Energy & Smart Grid',
    ],
  },
  {
    id: 'civil',
    name: 'Civil Engineering',
    shortName: 'CE',
    color: '#388E3C',
    bgColor: '#E8F5E9',
    icon: 'construct',
    generalTip: 'Structural Engineering + RCC Design = highest weightage. Geomatics and Environmental sections often catch aspirants unprepared.',
    coreSubjects: ['Structural Engineering', 'Geotechnical Engineering', 'Water Resources Engineering', 'Environmental Engineering'],
    allCoreSubjects: [
      'Structural Engineering',
      'Geotechnical Engineering',
      'Water Resources Engineering',
      'Environmental Engineering',
      'Transportation Engineering',
      'Geomatics Engineering',
      'Construction Technology & Project Management',
      'Irrigation Engineering & Hydrology',
    ],
  },
  {
    id: 'chemical',
    name: 'Chemical Engineering',
    shortName: 'CHE',
    color: '#7B1FA2',
    bgColor: '#F3E5F5',
    icon: 'flask',
    generalTip: 'Mass Transfer + Chemical Reaction Engineering are highest-yield. Process Calculations and Thermodynamics form the foundation for everything.',
    coreSubjects: ['Chemical Reaction Engineering', 'Mass Transfer', 'Heat Transfer', 'Fluid Mechanics & Mechanical Operations'],
    allCoreSubjects: [
      'Process Calculations & Thermodynamics',
      'Fluid Mechanics & Mechanical Operations',
      'Heat Transfer',
      'Mass Transfer',
      'Chemical Reaction Engineering',
      'Instrumentation & Process Control',
      'Plant Design & Economics',
      'Chemical Technology',
      'Process Safety & Environmental Engineering',
      'Plant Instrumentation & Process Analytics',
    ],
  },
  {
    id: 'cs',
    name: 'Computer Science / IT',
    shortName: 'CS',
    color: '#00796B',
    bgColor: '#E0F2F1',
    icon: 'code-slash',
    generalTip: 'DSA appears in every PSU CS exam. DBMS and OS are consistently second. Practice quick code-tracing for MCQs.',
    coreSubjects: ['Data Structures & Algorithms', 'DBMS', 'Operating Systems', 'Computer Networks'],
    allCoreSubjects: [
      'Digital Logic',
      'Computer Organization & Architecture',
      'Programming & Data Structures',
      'Algorithms',
      'Theory of Computation',
      'Compiler Design',
      'Operating Systems',
      'Databases',
      'Computer Networks',
      'Software Engineering & System Design',
    ],
  },
  {
    id: 'electronics',
    name: 'Electronics & Instrumentation',
    shortName: 'EC',
    color: '#E64A19',
    bgColor: '#FBE9E7',
    icon: 'hardware-chip',
    generalTip: 'Analog + Digital Circuits together = 50%+ in every EC exam. Networks, Signals & Systems is the highest-yield theory section.',
    coreSubjects: ['Analog Circuits', 'Digital Circuits', 'Networks, Signals & Systems', 'Control Systems'],
    allCoreSubjects: [
      'Networks, Signals & Systems',
      'Electronic Devices',
      'Analog Circuits',
      'Digital Circuits',
      'Control Systems',
      'Communications',
      'Electromagnetics',
      'Microprocessors & Embedded Systems',
      'VLSI Design',
    ],
  },
  {
    id: 'metallurgy',
    name: 'Metallurgy Engineering',
    shortName: 'MET',
    color: '#5D4037',
    bgColor: '#EFEBE9',
    icon: 'layers',
    generalTip: 'Iron-Carbon diagram + heat treatment appears in every exam. Extractive metallurgy is a score differentiator that few aspirants prepare well.',
    coreSubjects: ['Physical Metallurgy', 'Extractive Metallurgy', 'Mechanical Metallurgy', 'Manufacturing Processes'],
    allCoreSubjects: [
      'Metallurgical Thermodynamics & Rate Processes',
      'Mineral Processing & Extractive Metallurgy',
      'Physical Metallurgy',
      'Mechanical Metallurgy',
      'Manufacturing Processes',
      'Non-Destructive Testing & Quality Control',
      'Corrosion Engineering',
    ],
  },
  {
    id: 'mining',
    name: 'Mining Engineering',
    shortName: 'MN',
    color: '#455A64',
    bgColor: '#ECEFF1',
    icon: 'trending-down',
    generalTip: 'Mining Methods + Ventilation = ~50% of technical marks. Mine Safety & Legislation carries guaranteed memory-based marks — never skip it.',
    coreSubjects: ['Mining Methods & Machinery', 'Mine Ventilation', 'Geomechanics & Ground Control', 'Mine Safety & Legislation'],
    allCoreSubjects: [
      'Mining Geology & Mineralogy',
      'Mine Surveying',
      'Geomechanics & Ground Control',
      'Mining Methods & Machinery',
      'Mine Ventilation',
      'Underground Hazards & Safety',
      'Drilling & Blasting',
      'Mine Planning & Economics',
      'Mine Safety & Legislation',
      'Environmental Engineering in Mining',
    ],
  },
  {
    id: 'petroleum',
    name: 'Petroleum Engineering',
    shortName: 'PE',
    color: '#F9A825',
    bgColor: '#FFFDE7',
    icon: 'water',
    generalTip: 'Reservoir Engineering is the highest-yield area. Drilling fluids and well control are ONGC/GAIL exam staples.',
    coreSubjects: ['Reservoir Engineering', 'Drilling Engineering', 'Production Engineering', 'Petroleum Formation Evaluation'],
    allCoreSubjects: [
      'Petroleum Exploration',
      'Drilling Engineering',
      'Reservoir Engineering',
      'Production Engineering',
      'Petroleum Formation Evaluation',
      'Well Testing & Workover',
      'Offshore Operations',
      'Enhanced Oil Recovery',
      'Natural Gas Engineering',
      'Surface Facilities & Gas Processing',
      'HSE in Oil & Gas',
    ],
  },
  {
    id: 'geophysics',
    name: 'Geophysics',
    shortName: 'GEO',
    color: '#558B2F',
    bgColor: '#F1F8E9',
    icon: 'earth',
    generalTip: 'Seismic methods dominate ONGC GEO paper. Well logging and gravity-magnetic methods complement it in every exam.',
    coreSubjects: ['Seismic Methods', 'Well Logging', 'Gravity & Magnetic Methods', 'Electrical & EM Methods'],
    allCoreSubjects: [
      'Solid-Earth Geophysics',
      'Geophysical Signal Processing',
      'Seismic Methods',
      'Gravity & Magnetic Methods',
      'Electrical & Electromagnetic Methods',
      'Well Logging',
      'Radioactive Methods',
      'Applied Geophysics in Petroleum Exploration',
    ],
  },
  {
    id: 'hr_finance',
    name: 'HR / Finance / Management',
    shortName: 'HR',
    color: '#AD1457',
    bgColor: '#FCE4EC',
    icon: 'people',
    generalTip: 'Labour Laws (EPF, ESI, Factories Act) + Financial ratios are the highest-tested areas. Industrial Relations and OD questions are reliably scoring.',
    coreSubjects: ['Human Resource Management', 'Industrial Relations & Labour Laws', 'Financial Management', 'Organisational Behaviour'],
    allCoreSubjects: [
      'General Management',
      'Human Resource Management',
      'Human Resource Development',
      'Organisational Behaviour',
      'Industrial Relations',
      'Labour Legislation & Laws',
      'Labour Welfare & Social Security',
      'Financial Management',
      'Accounting & Taxation',
      'Operations Research & Business Statistics',
    ],
  },
];

export const getBranch = (id: string): BranchConfig | undefined =>
  BRANCHES.find(b => b.id === id);
