export type Topic = {
  id: string;
  title: string;
  subtopics: string[];
  estimatedQCount: number;
  tags: ('formula-heavy' | 'numerical' | 'conceptual' | 'memory' | 'graph-reading')[];
};

export const mechanicalTopics: Topic[] = [
  { id: 'mech_thermo', title: 'Thermodynamics', estimatedQCount: 8, tags: ['formula-heavy', 'numerical'],
    subtopics: ['Laws of Thermodynamics', 'Carnot & Rankine Cycle', 'Refrigeration & AC (VCR, VCE)', 'IC Engines — Otto, Diesel, Dual', 'Gas Turbines & Brayton Cycle', 'Steam Tables'],
  },
  { id: 'mech_fluid', title: 'Fluid Mechanics & Machinery', estimatedQCount: 8, tags: ['formula-heavy', 'numerical'],
    subtopics: ['Fluid Properties & Statics', "Bernoulli's Equation", 'Flow Measurement (Venturimeter, Pitot)', 'Laminar & Turbulent Flow', 'Centrifugal Pumps & Turbines (Pelton, Francis, Kaplan)'],
  },
  { id: 'mech_som', title: 'Strength of Materials', estimatedQCount: 7, tags: ['formula-heavy', 'numerical'],
    subtopics: ['Stress, Strain & Elastic Constants', 'Bending Moment & Shear Force Diagrams', 'Torsion of Shafts', 'Columns & Buckling', 'Pressure Vessels'],
  },
  { id: 'mech_heat', title: 'Heat Transfer', estimatedQCount: 6, tags: ['formula-heavy', 'numerical'],
    subtopics: ['Conduction — Fourier Law', 'Convection — Newton Law', 'Radiation — Stefan-Boltzmann', 'Heat Exchangers (LMTD, NTU)', 'Extended Surfaces & Fins'],
  },
  { id: 'mech_tom', title: 'Theory of Machines', estimatedQCount: 6, tags: ['conceptual', 'formula-heavy'],
    subtopics: ['Kinematics of Mechanisms', 'Gear Trains — Compound, Epicyclic', 'Flywheel & Governors', 'Balancing — Rotating & Reciprocating Masses', 'Vibrations — Free, Forced, Damped'],
  },
  { id: 'mech_mfg', title: 'Manufacturing & Production Engineering', estimatedQCount: 8, tags: ['conceptual', 'memory'],
    subtopics: ['Casting & Metal Forming (Forging, Rolling)', 'Welding — Types, Defects', 'Metal Cutting — Tool Geometry, Cutting Forces', 'Lathe, Milling, Drilling', 'CNC & Metrology'],
  },
  { id: 'mech_ind', title: 'Industrial Engineering', estimatedQCount: 5, tags: ['numerical', 'conceptual'],
    subtopics: ['Work Study & Method Study', 'Inventory Control — EOQ, ABC', 'Production Planning & Control', 'PERT & CPM', 'Quality Control — Control Charts'],
  },
  { id: 'mech_mat', title: 'Material Science', estimatedQCount: 4, tags: ['conceptual', 'memory'],
    subtopics: ['Crystal Structures', 'Iron-Carbon Phase Diagram', 'Heat Treatment', 'Fatigue & Creep', 'Non-Ferrous Alloys'],
  },
];

export const electricalTopics: Topic[] = [
  { id: 'elec_circuits', title: 'Electric Circuits', estimatedQCount: 10, tags: ['formula-heavy', 'numerical'],
    subtopics: ['KVL, KCL, Mesh & Node Analysis', 'Thevenin, Norton, Superposition Theorems', 'AC Circuits — Phasors, Impedance, Power Factor', 'Resonance', 'Transient Analysis — RC, RL, RLC'],
  },
  { id: 'elec_machines', title: 'Electrical Machines', estimatedQCount: 12, tags: ['conceptual', 'formula-heavy'],
    subtopics: ['DC Machines — Types, Characteristics, Speed Control', 'Transformers — OC/SC Tests, Efficiency', 'Induction Motors — Torque-Speed, Starting', 'Synchronous Machines', 'Special Machines — Stepper, BLDC'],
  },
  { id: 'elec_power', title: 'Power Systems', estimatedQCount: 10, tags: ['formula-heavy', 'numerical'],
    subtopics: ['Transmission Line Parameters', 'Per Unit System', 'Load Flow Analysis', 'Fault Analysis (Symmetrical & Unsymmetrical)', 'Power System Protection — Relays, CB'],
  },
  { id: 'elec_control', title: 'Control Systems', estimatedQCount: 8, tags: ['formula-heavy', 'numerical'],
    subtopics: ['Transfer Functions & Block Diagrams', 'Time Domain Analysis', 'Bode Plot, Nyquist, Root Locus', 'PID Compensators', 'State Space Analysis'],
  },
  { id: 'elec_pe', title: 'Power Electronics', estimatedQCount: 8, tags: ['conceptual', 'formula-heavy'],
    subtopics: ['Thyristors — SCR, TRIAC, DIAC', 'Rectifiers — Half/Full Wave, Controlled', 'Inverters — VSI, CSI', 'DC-DC Converters — Buck, Boost', 'AC & DC Drives'],
  },
  { id: 'elec_meas', title: 'Measurements & Instrumentation', estimatedQCount: 6, tags: ['conceptual', 'memory'],
    subtopics: ['Errors in Measurement', 'Bridges — Wheatstone, Maxwell', 'Transducers — LVDT, Strain Gauge, Thermocouple', 'CRO & Energy Meters'],
  },
  { id: 'elec_emf', title: 'Electromagnetic Fields', estimatedQCount: 6, tags: ['formula-heavy', 'conceptual'],
    subtopics: ["Maxwell's Equations", 'Gauss, Faraday, Ampere Laws', 'Wave Propagation & Poynting Vector', 'Inductance & Capacitance Calculation'],
  },
];

export const civilTopics: Topic[] = [
  { id: 'civil_struct', title: 'Structural Analysis', estimatedQCount: 10, tags: ['formula-heavy', 'numerical'],
    subtopics: ['Static & Kinematic Indeterminacy', 'Method of Sections & Joints', 'Slope Deflection & Moment Distribution', 'Influence Lines', 'Matrix Methods'],
  },
  { id: 'civil_rcc', title: 'RCC & Steel Design', estimatedQCount: 8, tags: ['formula-heavy', 'numerical'],
    subtopics: ['Limit State Design (IS 456)', 'Flexure, Shear, Torsion in Beams', 'Design of Columns & Footings', 'Steel Design (IS 800)', 'Welded & Bolted Connections'],
  },
  { id: 'civil_geo', title: 'Geotechnical Engineering', estimatedQCount: 8, tags: ['numerical', 'conceptual'],
    subtopics: ['Soil Classification & Phase Relations', 'Permeability & Seepage', 'Consolidation & Settlement', 'Shear Strength — Mohr-Coulomb', 'Bearing Capacity — Terzaghi'],
  },
  { id: 'civil_fluid', title: 'Fluid Mechanics & Hydraulics', estimatedQCount: 8, tags: ['formula-heavy', 'numerical'],
    subtopics: ["Bernoulli's Theorem", 'Flow Through Pipes', 'Open Channel Flow — Manning Equation', 'Hydraulic Turbines & Pumps', 'Notches & Weirs'],
  },
  { id: 'civil_survey', title: 'Surveying', estimatedQCount: 4, tags: ['conceptual', 'memory'],
    subtopics: ['Levelling & Contouring', 'Theodolite & Compass Survey', 'Errors & Adjustments', 'Remote Sensing & GIS Basics'],
  },
  { id: 'civil_transport', title: 'Transportation Engineering', estimatedQCount: 5, tags: ['memory', 'conceptual'],
    subtopics: ['Highway Geometric Design', 'Pavement Design — Flexible & Rigid', 'Traffic Engineering', 'IRC Codes'],
  },
  { id: 'civil_env', title: 'Environmental Engineering', estimatedQCount: 5, tags: ['conceptual', 'memory'],
    subtopics: ['Water Treatment — Coagulation, Filtration, Chlorination', 'Sewage Treatment — BOD, COD, Activated Sludge', 'Air Pollution Control', 'Solid Waste Management'],
  },
];

export const chemicalTopics: Topic[] = [
  { id: 'chem_fluid', title: 'Fluid Mechanics', estimatedQCount: 8, tags: ['formula-heavy', 'numerical'],
    subtopics: ["Bernoulli's Equation", 'Pipe Flow & Losses', 'Pumps & Compressors', 'Flow Measurement', 'Fluidization'],
  },
  { id: 'chem_heat', title: 'Heat Transfer', estimatedQCount: 8, tags: ['formula-heavy', 'numerical'],
    subtopics: ['Conduction, Convection, Radiation', 'Heat Exchangers — LMTD, NTU', 'Evaporators & Condensers'],
  },
  { id: 'chem_mass', title: 'Mass Transfer', estimatedQCount: 8, tags: ['formula-heavy', 'conceptual'],
    subtopics: ['Diffusion — Fick Law', 'Distillation — McCabe-Thiele', 'Absorption & Stripping', 'Extraction & Leaching', 'Drying'],
  },
  { id: 'chem_rxn', title: 'Chemical Reaction Engineering', estimatedQCount: 8, tags: ['formula-heavy', 'numerical'],
    subtopics: ['Reaction Kinetics & Rate Laws', 'Ideal Reactors — CSTR, PFR, Batch', 'Non-Ideal Reactors & RTD', 'Heterogeneous Catalysis'],
  },
  { id: 'chem_thermo', title: 'Chemical Thermodynamics', estimatedQCount: 6, tags: ['formula-heavy', 'conceptual'],
    subtopics: ['Phase Equilibria & VLE', 'Equations of State', 'Activity Coefficients', 'Reaction Equilibrium'],
  },
  { id: 'chem_process', title: 'Process Control', estimatedQCount: 6, tags: ['conceptual', 'formula-heavy'],
    subtopics: ['P&ID Symbols', 'PID Controllers', 'Control Loops', 'Process Dynamics', 'Stability Analysis'],
  },
  { id: 'chem_tech', title: 'Chemical Technology', estimatedQCount: 6, tags: ['memory', 'conceptual'],
    subtopics: ['Petroleum Refining Processes', 'Fertilizer & Ammonia Production', 'Polymer Manufacturing', 'Chlor-Alkali Industry'],
  },
];

export const csTopics: Topic[] = [
  { id: 'cs_ds', title: 'Data Structures & Algorithms', estimatedQCount: 10, tags: ['conceptual', 'numerical'],
    subtopics: ['Arrays, Linked Lists, Stacks, Queues', 'Trees — BST, AVL, Heap', 'Graphs — BFS, DFS, Shortest Path', 'Sorting & Searching', 'Time & Space Complexity'],
  },
  { id: 'cs_dbms', title: 'Database Management Systems', estimatedQCount: 8, tags: ['conceptual', 'memory'],
    subtopics: ['ER Model & Relational Algebra', 'SQL — DDL, DML, DCL', 'Normalization — 1NF to BCNF', 'Transaction Management & ACID', 'Indexing & B+ Trees'],
  },
  { id: 'cs_os', title: 'Operating Systems', estimatedQCount: 8, tags: ['conceptual', 'memory'],
    subtopics: ['Process Scheduling', 'Memory Management — Paging, Segmentation', 'Deadlock Detection & Prevention', 'File Systems'],
  },
  { id: 'cs_networks', title: 'Computer Networks', estimatedQCount: 8, tags: ['conceptual', 'memory'],
    subtopics: ['OSI & TCP/IP Models', 'IP Addressing & Subnetting', 'Routing Protocols — OSPF, RIP, BGP', 'TCP vs UDP', 'HTTP, DNS, DHCP'],
  },
  { id: 'cs_prog', title: 'Programming & OOP', estimatedQCount: 8, tags: ['conceptual', 'numerical'],
    subtopics: ['C/C++ Fundamentals', 'OOP — Inheritance, Polymorphism', 'Pointers & Memory Management', 'Java Basics'],
  },
  { id: 'cs_co', title: 'Computer Organization & Architecture', estimatedQCount: 6, tags: ['conceptual', 'memory'],
    subtopics: ['Number Systems & Boolean Algebra', 'Logic Gates & Circuits', 'CPU Architecture & Pipelining', 'Memory Hierarchy'],
  },
];

export const electronicsTopics: Topic[] = [
  { id: 'ec_analog', title: 'Analog Electronics', estimatedQCount: 10, tags: ['formula-heavy', 'conceptual'],
    subtopics: ['Diodes — Rectifiers, Zener', 'BJT & MOSFET Amplifiers', 'Op-Amp Configurations', 'Oscillators — LC, RC', 'Power Amplifiers'],
  },
  { id: 'ec_digital', title: 'Digital Electronics', estimatedQCount: 8, tags: ['conceptual', 'numerical'],
    subtopics: ['Boolean Algebra & K-Map', 'Combinational Circuits — MUX, Decoder', 'Sequential Circuits — Flip Flops, Counters', 'ADC & DAC Converters'],
  },
  { id: 'ec_control', title: 'Control Systems', estimatedQCount: 8, tags: ['formula-heavy', 'numerical'],
    subtopics: ['Transfer Functions', 'Time & Frequency Response', 'Root Locus, Bode Plot, Nyquist', 'PID Controllers'],
  },
  { id: 'ec_comm', title: 'Communication Systems', estimatedQCount: 8, tags: ['formula-heavy', 'conceptual'],
    subtopics: ['AM, FM, PM Modulation', 'Sampling Theorem & PCM', 'Digital Modulation — ASK, FSK, PSK, QAM', 'Multiplexing — TDM, FDM'],
  },
  { id: 'ec_signal', title: 'Signals & Systems', estimatedQCount: 6, tags: ['formula-heavy', 'numerical'],
    subtopics: ['Fourier Series & Transform', 'Laplace & Z-Transform', 'Convolution & Correlation', 'LTI Systems'],
  },
  { id: 'ec_instr', title: 'Instrumentation', estimatedQCount: 6, tags: ['conceptual', 'memory'],
    subtopics: ['Sensors — LVDT, RTD, Thermocouple', 'Signal Conditioning', 'Data Acquisition Systems', 'Industrial Instrumentation'],
  },
];

export const metallurgyTopics: Topic[] = [
  { id: 'met_phase', title: 'Physical Metallurgy', estimatedQCount: 10, tags: ['conceptual', 'memory'],
    subtopics: ['Crystal Structures — BCC, FCC, HCP', 'Iron-Carbon Phase Diagram', 'Heat Treatment', 'TTT & CCT Diagrams', 'Grain Growth'],
  },
  { id: 'met_mech', title: 'Mechanical Metallurgy', estimatedQCount: 8, tags: ['formula-heavy', 'numerical'],
    subtopics: ['Deformation — Slip & Twinning', 'Creep & Fatigue', 'Fracture Mechanics', 'Hardness Testing'],
  },
  { id: 'met_extract', title: 'Extractive Metallurgy', estimatedQCount: 8, tags: ['memory', 'conceptual'],
    subtopics: ['Iron & Steel Making — Blast Furnace, BOF, EAF', 'Non-Ferrous Extraction — Al, Cu, Zn', 'Hydrometallurgy & Electrometallurgy'],
  },
  { id: 'met_mfg', title: 'Manufacturing Processes', estimatedQCount: 6, tags: ['conceptual', 'memory'],
    subtopics: ['Casting — Sand, Investment', 'Metal Working — Rolling, Forging', 'Welding Metallurgy', 'Powder Metallurgy'],
  },
];

export const miningTopics: Topic[] = [
  { id: 'mine_methods', title: 'Mining Methods', estimatedQCount: 12, tags: ['conceptual', 'memory'],
    subtopics: ['Surface Mining — Open Cast, Strip', 'Underground Mining — Room & Pillar, Long Wall', 'Shaft Sinking & Drifting', 'Stoping Methods', 'Mine Planning'],
  },
  { id: 'mine_geotech', title: 'Mine Geotechnology & Rock Mechanics', estimatedQCount: 8, tags: ['formula-heavy', 'conceptual'],
    subtopics: ['Rock Properties & Classification', 'Rock Failures — Slope Stability', 'Support Design — Pillars, Bolts'],
  },
  { id: 'mine_ventilation', title: 'Mine Ventilation & Environment', estimatedQCount: 8, tags: ['formula-heavy', 'conceptual'],
    subtopics: ['Natural & Mechanical Ventilation', 'Mine Gases — Methane, CO, CO₂', 'Dust Control', 'Ventilation Network Analysis'],
  },
  { id: 'mine_explosive', title: 'Drilling & Blasting', estimatedQCount: 6, tags: ['conceptual', 'memory'],
    subtopics: ['Types of Explosives', 'Blast Design — Burden, Spacing', 'Initiating Devices', 'Controlled Blasting'],
  },
  { id: 'mine_equip', title: 'Mining Equipment & Transport', estimatedQCount: 6, tags: ['memory', 'conceptual'],
    subtopics: ['Loaders & Dumpers', 'Continuous Miners & Shearers', 'Belt Conveyors', 'Mine Hoisting Systems'],
  },
];

export const petroleumTopics: Topic[] = [
  { id: 'petro_reservoir', title: 'Reservoir Engineering', estimatedQCount: 12, tags: ['formula-heavy', 'numerical'],
    subtopics: ['Porosity & Permeability', "Darcy's Law", 'Material Balance Equations', 'Enhanced Oil Recovery', 'Pressure Transient Analysis'],
  },
  { id: 'petro_drill', title: 'Drilling Engineering', estimatedQCount: 10, tags: ['conceptual', 'formula-heavy'],
    subtopics: ['Rotary Drilling System', 'Drilling Fluids', 'Casing Design & Cementing', 'Well Control — BOP', 'Directional Drilling'],
  },
  { id: 'petro_prod', title: 'Production Engineering', estimatedQCount: 8, tags: ['conceptual', 'formula-heavy'],
    subtopics: ['Well Completion & Perforation', 'Artificial Lift — ESP, Gas Lift', 'Flow Assurance', 'Surface Separation Facilities'],
  },
  { id: 'petro_refine', title: 'Petroleum Refining', estimatedQCount: 8, tags: ['conceptual', 'memory'],
    subtopics: ['Crude Distillation — ADU, VDU', 'Cracking — FCC, Hydrocracking', 'Reforming & Isomerization', 'Desulfurization'],
  },
];

export const geophysicsTopics: Topic[] = [
  { id: 'geo_seismic', title: 'Seismic Methods', estimatedQCount: 12, tags: ['conceptual', 'formula-heavy'],
    subtopics: ['Seismic Wave Theory', 'Refraction & Reflection Methods', 'Data Acquisition', 'Seismic Processing — NMO, Migration', 'Interpretation'],
  },
  { id: 'geo_gravity', title: 'Gravity & Magnetic Methods', estimatedQCount: 8, tags: ['formula-heavy', 'conceptual'],
    subtopics: ['Gravity Survey Corrections', 'Gravity Anomaly Interpretation', 'Magnetic Properties of Rocks', 'Aeromagnetic Surveys'],
  },
  { id: 'geo_electrical', title: 'Electrical & EM Methods', estimatedQCount: 8, tags: ['conceptual', 'formula-heavy'],
    subtopics: ['Resistivity Surveys', 'IP & SP Methods', 'EM Methods — TDEM, FDEM', 'Ground Penetrating Radar'],
  },
  { id: 'geo_well', title: 'Well Logging', estimatedQCount: 8, tags: ['conceptual', 'memory'],
    subtopics: ['Gamma Ray & SP Logs', 'Resistivity Logs', 'Density & Neutron Logs', 'Sonic Log', 'Log Interpretation'],
  },
];

export const hrFinanceTopics: Topic[] = [
  { id: 'hr_mgmt', title: 'Human Resource Management', estimatedQCount: 10, tags: ['conceptual', 'memory'],
    subtopics: ['Recruitment & Selection', 'Training & Development', 'Performance Appraisal', 'Labour Laws — EPF, ESI, Factories Act', 'Industrial Relations'],
  },
  { id: 'hr_finance', title: 'Financial Management', estimatedQCount: 10, tags: ['formula-heavy', 'numerical'],
    subtopics: ['Financial Statement Analysis', 'Ratio Analysis', 'Capital Budgeting — NPV, IRR', 'Working Capital Management', 'Cost Accounting'],
  },
  { id: 'hr_obm', title: 'Organizational Behavior', estimatedQCount: 8, tags: ['conceptual', 'memory'],
    subtopics: ['Motivation Theories — Maslow, Herzberg', 'Leadership Styles', 'Organizational Culture', 'Communication in Organizations'],
  },
  { id: 'hr_mktg', title: 'Marketing Management', estimatedQCount: 6, tags: ['conceptual', 'memory'],
    subtopics: ['Marketing Mix — 4Ps', 'Consumer Behavior', 'Market Segmentation & Positioning', 'Digital Marketing'],
  },
  { id: 'hr_ca', title: 'Accounting & Taxation', estimatedQCount: 6, tags: ['numerical', 'memory'],
    subtopics: ['Double Entry System', 'Balance Sheet & P&L', 'GST Basics', 'Income Tax Heads', 'Company Law Basics'],
  },
];

export const domainTopicMap: Record<string, Topic[]> = {
  mechanical:  mechanicalTopics,
  electrical:  electricalTopics,
  civil:       civilTopics,
  chemical:    chemicalTopics,
  cs:          csTopics,
  electronics: electronicsTopics,
  metallurgy:  metallurgyTopics,
  mining:      miningTopics,
  petroleum:   petroleumTopics,
  geophysics:  geophysicsTopics,
  hr_finance:  hrFinanceTopics,
};
